---
title: "Preliminary Report"
author: "Dylan Denner & Jackson Tucker"
date: "4/19/2021"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preperation for Presentation


```{r, echo=FALSE}
setwd("C:/Users/dylan/Documents/R/MATH5530/Project/MATH5530/SCRIPTS/")
library(dplyr)
library(tidycensus)
library(tidyverse)
library(tidyr)
library(readxl)
library(readr)
library(gridExtra)
library(ggpubr)
library(MASS)
library(car)
library(lmtest)
library(dplyr)
library(tidycensus)
library(tidyverse)
library(tidyr)
library(readxl)
library(gam)
library(mgcv)

```



```{r}
library(tidycensus)

poverty_by_sex_edu_attainment <- get_acs(
  geography = "school district (unified)", 
  variables = c(total_population = "B17003_001",
                below_poverty_num = "B17003_002",
                below_poverty_num_men = "B17003_003",
                M_below_poverty_less_than_HS = "B17003_004",
                M_below_poverty_HS = "B17003_005",
                M_below_poverty_some_college = "B17003_006",
                M_below_poverty_bachelor_plus = "B17003_007",
                below_poverty_num_women = "B17003_008",
                W_below_poverty_less_than_HS = "B17003_009",
                W_below_poverty_HS = "B17003_010",
                W_below_poverty_some_college = "B17003_011",
                W_below_poverty_bachelor_plus = "B17003_012",
                above_poverty_num = "B17003_013",
                above_poverty_num_men = "B17003_014",
                M_above_poverty_less_than_HS = "B17003_015",
                M_above_poverty_HS = "B17003_016",
                M_above_poverty_some_college = "B17003_017",
                M_above_poverty_bachelor_plus = "B17003_018",
                above_poverty_num_women = "B17003_019",
                W_above_poverty_less_than_HS = "B17003_020",
                W_above_poverty_HS = "B17003_021",
                W_above_poverty_some_college = "B17003_022",
                W_above_poverty_bachelor_plus = "B17003_023"),
  state = "OH", 
  year = 2019)
```
```{r}
head(poverty_by_sex_edu_attainment)
dim(poverty_by_sex_edu_attainment)
length(unique(poverty_by_sex_edu_attainment$NAME))
```


```{r}
poverty_by_sex_edu_attainment[,-c(5)]

```

```{r}
poverty_by_sex_edu_attainment <- spread(poverty_by_sex_edu_attainment, variable, estimate)

head(poverty_by_sex_edu_attainment)
dim(poverty_by_sex_edu_attainment)


```

```{r}
mod_poverty_by_sex_edu_attainment <- poverty_by_sex_edu_attainment %>% mutate(
  "tot_less_than_HS" = W_below_poverty_less_than_HS + M_below_poverty_less_than_HS + 
                      W_above_poverty_less_than_HS + M_above_poverty_less_than_HS,
  "tot_HS" = W_below_poverty_HS + M_below_poverty_HS + 
            W_above_poverty_HS + M_above_poverty_HS,
  "tot_some_college" = W_below_poverty_some_college + M_below_poverty_some_college + 
                    W_above_poverty_some_college + M_above_poverty_some_college,
  "tot_bachelor_plus" = W_below_poverty_bachelor_plus + M_below_poverty_bachelor_plus + 
                      W_above_poverty_bachelor_plus + M_above_poverty_bachelor_plus,
  "tot_HS_PLUS" = tot_HS + tot_some_college + tot_bachelor_plus,
  "poverty_percentage" = below_poverty_num/total_population,
  "HS_PLUS_percentage" = tot_HS_PLUS/total_population)

```

```{r}
mod_poverty_by_sex_edu_attainment <- dplyr::select(
  mod_poverty_by_sex_edu_attainment,
  NAME,
  total_population,
  below_poverty_num,
  above_poverty_num,
  poverty_percentage,
  tot_less_than_HS,
  tot_HS,
  tot_some_college,
  tot_bachelor_plus,
  HS_PLUS_percentage
)

dim(mod_poverty_by_sex_edu_attainment)


```

```{r}
file_path <- "../DATA/BUILDING_OVERVIEW_1819.xlsx"
overview_data <- read_excel(file_path, sheet = "BUILDING_OVERVIEW")

file_path <- "../DATA/BUILDING_DISCIPLINE_1819.xlsx"
discipline_data <- read_excel(file_path, sheet = "DISCIPLINE")

```

```{r}
overview_data <- dplyr::select(
  overview_data,
  "Building IRN",
  "Building Name",
  "District Name",
  "County",
  "Region",
  "Enrollment 2018-2019",
  "Attendance Rate 2018-2019",
  "Chronic Absenteeism Percent 2018-2019"
)

overview_data[,6:8] <- sapply(overview_data[,6:8],as.numeric)

discipline_data[ discipline_data == "<10" ] <- "0"
discipline_data[,8:26] <- sapply(discipline_data[,8:26],as.numeric)
discipline_data <- discipline_data[,-26]
discipline_data <- subset(discipline_data, discipline_data$`Discpline Reason Description` == "Disobedient/Disruptive Behavior")


```

```{r}
discipline_data <- dplyr::select(
  discipline_data,
  "Building IRN",
  "Students Disciplined - Expulsions",
  "Students Disciplined - Out-of-School Suspensions",
  "Students Disciplined - In-School Suspensions"
)

```

```{r}
discipline_data <- discipline_data %>% mutate(
  "total_students_discipline" = (rowSums(discipline_data[,2:4])))

joined_df <- left_join(overview_data, discipline_data, by = "Building IRN")


```

```{r}
grouped_df <- joined_df %>%
  group_by(`District Name`, County, Region) %>%
  summarise(mean_enrollment = mean(`Enrollment 2018-2019`, na.rm = TRUE),
            mean_attendence = mean(`Attendance Rate 2018-2019`, na.rm = TRUE),
            mean_chronic_absenteesim = mean(`Chronic Absenteeism Percent 2018-2019`, na.rm = TRUE),
            mean_expulsions = mean(`Students Disciplined - Expulsions`, na.rm = TRUE),
            mean_out_of_school_suspensions = mean(`Students Disciplined - Out-of-School Suspensions`, na.rm = TRUE),
            mean_in_school_suspensions = mean(`Students Disciplined - In-School Suspensions`, na.rm = TRUE),
            mean_total_students_discipline = mean(`total_students_discipline`, na.rm = TRUE))

```

```{r}
file_path <- "../DATA/model_data_3_30.csv"
model_data <- read.csv(file_path)

ggplot(model_data, aes(x=poverty_percentage, y=HS_PLUS_percentage)) + geom_point() + 
  ggtitle("Poverty % vs. Educational Attainment %") +
  xlab("Poverty %") + 
  ylab("Educational Attainment %")


ggplot(model_data, aes(x=mean_total_students_discipline, y=HS_PLUS_percentage)) + geom_point() + 
  ggtitle("Mean Student Discipline vs. Educational Attainment %") +
  xlab("Mean Student Discipline") + 
  ylab("Educational Attainment %")


ggplot(model_data, aes(x=mean_chronic_absenteeism, y=HS_PLUS_percentage)) + geom_point() + 
  ggtitle("Mean Chronic Absenteeism % vs. Educational Attainment %") +
  xlab("Mean Chronic Absenteeism %") + 
  ylab("Educational Attainment %")

ggplot(model_data, aes(x=mean_attendance, y=HS_PLUS_percentage)) + geom_point() + 
  ggtitle("Mean Attendance % vs. Educational Attainment %") +
  xlab("Mean Attendance %") + 
  ylab("Educational Attainment %")

ggplot(model_data, aes(x=mean_enrollment, y=HS_PLUS_percentage)) + geom_point() + 
  ggtitle("Mean Enrollment vs. Educational Attainment %") +
  xlab("Mean Enrollment") + 
  ylab("Educational Attainment %")


```

```{r}

POVERTY_lm <- lm(log(HS_PLUS_percentage) ~ poverty_percentage, data = model_data)
DISCIPLINE_lm <- lm(log(HS_PLUS_percentage) ~ mean_total_students_discipline, data = model_data)
CHRONIC_lm <- lm(log(HS_PLUS_percentage) ~ mean_chronic_absenteeism, data = model_data)
ATTENDANCE_lm <- lm(log(HS_PLUS_percentage) ~ mean_attendance, data = model_data)
ENROLLMENT_lm <- lm(log(HS_PLUS_percentage) ~ mean_enrollment, data = model_data)

 mod_model_data <- subset(model_data, model_data$HS_PLUS_percentage > 0.65)

POVERTY_lm_mod <- lm(log(HS_PLUS_percentage) ~ poverty_percentage, data = mod_model_data)
DISCIPLINE_lm_mod <- lm(log(HS_PLUS_percentage) ~ mean_total_students_discipline, data = mod_model_data)
CHRONIC_lm_mod <- lm(log(HS_PLUS_percentage) ~ mean_chronic_absenteeism, data = mod_model_data)
ATTENDANCE_lm_mod <- lm(log(HS_PLUS_percentage) ~ mean_attendance, data = mod_model_data)
ENROLLMENT_lm_mod <- lm(log(HS_PLUS_percentage) ~ mean_enrollment, data = mod_model_data)


```

```{r}
DISCIPLINE_sresid <- studres(DISCIPLINE_lm)
shapiro.test(DISCIPLINE_sresid)

```

```{r}
DISCIPLINE_sresid_mod <- studres(DISCIPLINE_lm_mod)
shapiro.test(DISCIPLINE_sresid_mod)
```

```{r}
#heterodastic
ncvTest(POVERTY_lm)
ncvTest(POVERTY_lm_mod)
```

```{r}
#homoscedastic
ncvTest(DISCIPLINE_lm)
ncvTest(DISCIPLINE_lm_mod)
```

```{r}
#heteroscedastic
ncvTest(CHRONIC_lm)
ncvTest(CHRONIC_lm_mod)
```

```{r}
#homoscedastic
ncvTest(ATTENDANCE_lm)
ncvTest(ATTENDANCE_lm_mod)

```

```{r}
#heteroscedastic
ncvTest(ENROLLMENT_lm)
ncvTest(ENROLLMENT_lm_mod)

```

```{r}
raw_lm <- lm(log(HS_PLUS_percentage) ~ poverty_percentage* mean_chronic_absenteeism + mean_enrollment, data = model_data)
summary(raw_lm)
```

```{r}
new_lm <- lm(log(HS_PLUS_percentage) ~ poverty_percentage* mean_chronic_absenteeism + mean_enrollment, data = mod_model_data)

summary(new_lm)
```

```{r}
new_lm_mod <- lm(log(HS_PLUS_percentage) ~ poverty_percentage* mean_chronic_absenteeism + mean_enrollment, data = mod_model_data)

plot(fitted(new_lm_mod), resid(new_lm_mod))


```


```{r}
new_lm_mod2 <- lm((((HS_PLUS_percentage ^ 7) - 1) / 7) ~ poverty_percentage* mean_chronic_absenteeism + mean_enrollment, data = mod_model_data)
summary(new_lm_mod2)
```

```{r}
plot(fitted(new_lm_mod2), resid(new_lm_mod2))

```

```{r}
new_sresid_mod2 <- studres(new_lm_mod2)
new_sresid_mod <- studres(new_lm_mod)
shapiro.test(new_sresid_mod2)
shapiro.test(new_sresid_mod)
```



```{r, warning=FALSE, message=FALSE}
attach(mod_model_data)
smooth_spline_poverty_cv <- smooth.spline(poverty_percentage, HS_PLUS_percentage, cv=TRUE)

smooth_spline_absenteeism_cv <- smooth.spline(mean_chronic_absenteeism, HS_PLUS_percentage, cv=TRUE)

smooth_spline_attendance_cv <- smooth.spline(mean_attendance, HS_PLUS_percentage, cv=TRUE)

smooth_spline_enrollment_cv <- smooth.spline(mean_enrollment, HS_PLUS_percentage, cv=TRUE)

smooth_spline_discipline_cv <- smooth.spline(mean_total_students_discipline, HS_PLUS_percentage, cv=TRUE)

smooth_spline_poverty_cv$df
smooth_spline_absenteeism_cv$df
smooth_spline_attendance_cv$df
smooth_spline_enrollment_cv$df
smooth_spline_discipline_cv$df
```

```{r}
gam_model <- gam(HS_PLUS_percentage ~ s(poverty_percentage) + s(mean_chronic_absenteeism) + s(mean_attendance) + s(mean_enrollment) + s(mean_total_students_discipline), data = mod_model_data)
summary(gam_model)
gam_model$coefficients
```

```{r}
gam.check(gam_model)
```

```{r}
plot(gam_model, se=TRUE, col="blue")
```

