---
title: "MATH 5530 Presentation"
author: "Jackson Tucker & Dylan Denner"
date: "4/6/2021"
output:
  powerpoint_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

...

## Research Questions

- ..
- ...
- ...

## Preliminary Analysis

- Pulling data
- Census Data
- Ohio Data

```{r}
setwd("C:/Users/dylan/Documents/R/MATH5530/Project/MATH5530/SCRIPTS/")
library(dplyr)
library(tidycensus)
library(tidyverse)
library(tidyr)
library(readxl)
poverty_by_sex_edu_attainment <- get_acs(
  geography = "school district (unified)", 
  variables = c(total_population = "B17003_001",
                below_poverty_num = "B17003_002",
                below_poverty_num_men = "B17003_003",
                M_below_poverty_less_than_HS = "B17003_004",
                M_below_poverty_HS = "B17003_005",
                M_below_poverty_some_college = "B17003_006",
                M_below_poverty_bachelor_plus = "B17003_007",
                below_poverty_num_women = "B17003_008",
                W_below_poverty_less_than_HS = "B17003_009",
                W_below_poverty_HS = "B17003_010",
                W_below_poverty_some_college = "B17003_011",
                W_below_poverty_bachelor_plus = "B17003_012",
                above_poverty_num = "B17003_013",
                above_poverty_num_men = "B17003_014",
                M_above_poverty_less_than_HS = "B17003_015",
                M_above_poverty_HS = "B17003_016",
                M_above_poverty_some_college = "B17003_017",
                M_above_poverty_bachelor_plus = "B17003_018",
                above_poverty_num_women = "B17003_019",
                W_above_poverty_less_than_HS = "B17003_020",
                W_above_poverty_HS = "B17003_021",
                W_above_poverty_some_college = "B17003_022",
                W_above_poverty_bachelor_plus = "B17003_023"),
  state = "OH", 
  year = 2019)

```

## In-depth Analysis

```{r}
plot(pressure)
```

## Conclusions and Future Work

## Data and Code